/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/modals`; params?: Router.UnknownInputParams; } | { pathname: `/components/modals`; params?: Router.UnknownInputParams; } | { pathname: `/telas/DeleteImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/UpdateImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/Impostos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigator/navigator`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/imoveisService`; params?: Router.UnknownInputParams; } | { pathname: `/telas/CadastroImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/home`; params?: Router.UnknownInputParams; } | { pathname: `/telas/ListaImoveis`; params?: Router.UnknownInputParams; } | { pathname: `/telas/login`; params?: Router.UnknownInputParams; } | { pathname: `/types/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/modals`; params?: Router.UnknownOutputParams; } | { pathname: `/components/modals`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/DeleteImovel`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/UpdateImovel`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/Impostos`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/navigator/navigator`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/services/imoveisService`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/CadastroImovel`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/home`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/ListaImoveis`; params?: Router.UnknownOutputParams; } | { pathname: `/telas/login`; params?: Router.UnknownOutputParams; } | { pathname: `/types/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/modals${`?${string}` | `#${string}` | ''}` | `/components/modals${`?${string}` | `#${string}` | ''}` | `/telas/DeleteImovel${`?${string}` | `#${string}` | ''}` | `/telas/UpdateImovel${`?${string}` | `#${string}` | ''}` | `/telas/Impostos${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/navigator/navigator${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/services/imoveisService${`?${string}` | `#${string}` | ''}` | `/telas/CadastroImovel${`?${string}` | `#${string}` | ''}` | `/telas/home${`?${string}` | `#${string}` | ''}` | `/telas/ListaImoveis${`?${string}` | `#${string}` | ''}` | `/telas/login${`?${string}` | `#${string}` | ''}` | `/types/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/modals`; params?: Router.UnknownInputParams; } | { pathname: `/components/modals`; params?: Router.UnknownInputParams; } | { pathname: `/telas/DeleteImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/UpdateImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/Impostos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigator/navigator`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/imoveisService`; params?: Router.UnknownInputParams; } | { pathname: `/telas/CadastroImovel`; params?: Router.UnknownInputParams; } | { pathname: `/telas/home`; params?: Router.UnknownInputParams; } | { pathname: `/telas/ListaImoveis`; params?: Router.UnknownInputParams; } | { pathname: `/telas/login`; params?: Router.UnknownInputParams; } | { pathname: `/types/types`; params?: Router.UnknownInputParams; };
    }
  }
}
